name: build-windows

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: |
            ~\AppData\Local\npm-cache
          key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Build Windows installer
        run: npm run build:win
        env:
          ELECTRON_BUILDER_CACHE: ${{ runner.temp }}\electron-builder
          ELECTRON_CACHE: ${{ runner.temp }}\electron

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pater-windows-dist
          path: dist/**
